set and get output helper methods
Telefonica/govice pull request #7
Opened 2018-03-27 10:36 UTC by martinilevi

2018-04-03 10:16 UTC, jlorgal requested changes

2018-04-03 10:16 UTC, jlorgal commented on log.go
> +// NewLoggerWithOutput to create a Logger to a different output than stdout.
I'd prefer to avoid a new constructor

2018-04-03 10:16 UTC, jlorgal commented on log.go
> +// SetOutput to set the log writer
Better to rename as SetWriter/GetWriter

2018-04-03 12:25 UTC, martinilevi commented on log.go
> +// NewLoggerWithOutput to create a Logger to a different output than stdout.
ok

2018-04-03 12:25 UTC, martinilevi commented on log.go
> +// SetOutput to set the log writer
ok

2018-04-04 08:23 UTC, jlorgal approved these changes

2018-04-04 08:24 UTC, merged